name: AIBuild
version: 2.0.0
main: com.example.aibuild.AIBuildPlugin
api-version: 1.20

commands:
  aibuild:
    description: Generate an AI building at your location
    usage: /aibuild <description|undo>

permissions:
  aibuild.use:
    default: op
